# Use root/example as user/password credentials
version: "3.3"

volumes:
  mongo_data:
    driver: local

services:
  app:
    build: .
    ports:
      - "5006:5005"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/var/lib/mongo/data
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
